---
# tasks file for node-exporter

- name: Check latest version of Node exporter if not define from monitoring
  ansible.builtin.shell: curl -s https://api.github.com/repos/prometheus/node_exporter/releases/latest | grep "tag_name" | awk '{print substr($2, 3, length($2)-4)}'
  register: node_exporter_latest
  when: hostvars['monitor']['node_exporter_latest_mon'] is not defined

- name: Get latest version of Node exporter from monitoring
  ansible.builtin.set_fact: 
    node_exporter_latest: "{{ hostvars['monitor']['node_exporter_latest_mon'] }}"
  when: hostvars['monitor']['node_exporter_latest_mon'] is defined

- name: Check installed version of Node exporter
  ansible.builtin.shell: node_exporter --version | grep node_exporter | awk '{print substr($3, 0, length($3))}'
  register: node_exporter_installed

- import_tasks: node-exporter-tasks.yml
  when: node_exporter_latest.stdout != node_exporter_installed.stdout
  