---
# tasks file for loki

- name: Get latest version of Loki
  ansible.builtin.shell: |
    wget $(curl -s https://api.github.com/repos/grafana/loki/releases/latest |grep "tag_name" | \
    awk '{print "https://github.com/grafana/loki/releases/download/" \
    substr($2, 2, length($2)-3) "/loki-linux-amd64.zip"}')
    unzip loki-linux-amd64.zip

- name: Copy files to /usr/local/bin
  become: true
  ansible.builtin.shell: |
    chmod +x "loki-linux-amd64"
    mv loki-linux-amd64 /usr/local/bin/loki

- name: Ensure group "loki" exists
  ansible.builtin.group:
    name: loki
    state: present

- name: Ensure user "loki" exists
  ansible.builtin.user:
    name: loki
    state: present
    group: loki

- name: Create /etc/loki/ if it does not exist
  ansible.builtin.file:
    path: /etc/loki/
    state: directory
    owner: loki
    group: loki
    mode: '0755'

- name: Clean up the download packages
  ansible.builtin.shell: 
    rm -rf ./loki*

- name: Check if service exists
  stat: 'path=/etc/systemd/system/loki.service'
  register: servicestatus

- name: Create service file for loki if it does not exist
  become: true
  ansible.builtin.template: 
    src: files/loki.service
    dest: /etc/systemd/system/loki.service
    force: yes
  when: not servicestatus.stat.exists

- name: Enable loki service and ensure it is not masked  if it does not exist
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
    name: loki
    enabled: yes
    masked: no
  when: not servicestatus.stat.exists